services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - .:/workspace
    tty: true
    command: streamlit run app/research_reader.py
